name: CD/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t mngerasimenko/todo-app:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        run: docker push mngerasimenko/todo-app:${{ github.sha }}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root
            docker pull mngerasimenko/todo-app:${{ github.sha }}
            docker stop todo-app || true
            docker rm todo-app || true
            docker run -d \
              --name todo-app \
              -p 8090:8090 \
              -e SPRING_DATASOURCE_URL='jdbc:mysql://mysql-db:3306/todo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC' -e SPRING_DATASOURCE_USERNAME=user -e SPRING_DATASOURCE_PASSWORD=user --network todo-network --restart unless-stopped mngerasimenko/todo-app:${{ github.sha }} \
              -e SPRING_DATASOURCE_USERNAME=user \
              -e SPRING_DATASOURCE_PASSWORD=user \
              --network todo-network \
              --restart unless-stopped \
              mngerasimenko/todo-app:${{ github.sha }}


